# Generated by Django 5.0.6 on 2024-06-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='items',
            field=models.ManyToManyField(related_name='items', to='items.item'),
        ),
    ]
