# Generated by Django 5.0.6 on 2024-06-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('AN', 'Anzoátegui'), ('AP', 'Apure'), ('AR', 'Aragua'), ('BA', 'Barinas'), ('BO', 'Bolívar'), ('CA', 'Carabobo'), ('CO', 'Cojedes'), ('DA', 'Delta Amacuro'), ('DC', 'Distrito Capital'), ('FA', 'Falcón'), ('GU', 'Guárico'), ('LA', 'Lara'), ('ME', 'Mérida'), ('MI', 'Miranda'), ('MO', 'Monagas'), ('NE', 'Nueva Esparta'), ('PO', 'Portuguesa'), ('SU', 'Sucre'), ('TA', 'Táchira'), ('TR', 'Trujillo'), ('VA', 'Vargas'), ('YA', 'Yaracuy'), ('ZU', 'Zulia')], max_length=2, null=True),
        ),
    ]
